image: node:6.4

stages:
  - test
  - deploy

before_script:
  - apt-get update -qy
  - npm install

unit_tests:
  stage: test
  script:
    - npm run test
  cache:
    paths:
    - node_modules/
  only:
    - master
    
staging:
  stage: deploy
  script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y heroku-toolbelt
    - export HEROKU_API_KEY=[YOUR API KEY]
    - heroku login
    - heroku git:remote -a your-app-name
    - git push heroku master
  only:
    - master
